In [3]:
import struct
import numpy as np
import torch
import torchvision

# files = ["fashion-mnist_test.csv", "fashion-mnist_train.csv"]
train_dataset = torchvision.datasets.FashionMNIST(".", train=True, download=True, transform=torchvision.transforms.ToTensor())
test_dataset = torchvision.datasets.FashionMNIST(".", train=False, download=True, transform=torchvision.transforms.ToTensor())

def dump_to_bin(dataset, basename):
    xs, ys = [], []
    data_loader = torch.utils.data.DataLoader(
        dataset,
        batch_size=1,
        shuffle=False,
        drop_last=False
    )
    for x,y in data_loader:
        xs.append(x)
        ys.append(y)

    xs = torch.cat(xs, dim=0)
    ys = torch.cat(ys, dim=0)
    print(xs.shape, xs.dtype, ys.shape, ys.dtype)
    # data = data.split("\n")[1:-1]
    # for line in data:
    #     label, *pixels = line.split(",")
    #     xs.append([float(int(v)) / 255.0 for v in pixels])
    #     ys.append(int(label))
        
    xs = xs.numpy().astype(np.float32) 
    ys = ys.numpy().astype(np.uint8)
    
    xs = xs.tobytes()
    ys = ys.tobytes()
    
    with open(basename + "-data.bin", "wb") as f:
        f.write(xs)
    with open(basename + "-labels.bin", "wb") as f:
        f.write(ys)

dump_to_bin(train_dataset, "train")
dump_to_bin(test_dataset, "test")

torch.Size([60000, 1, 28, 28]) torch.float32 torch.Size([60000]) torch.int64
torch.Size([10000, 1, 28, 28]) torch.float32 torch.Size([10000]) torch.int64


In [2]:
# import torch
# n = torch.arange(30)
# n = n.reshape((5,3,2))
# print(n.shape)
# print(n.flatten())
# n = n.permute((0,1,2))
# print(n[1][1][2])
# print(n.shape)
# n.flatten()

In [3]:
# perm = (3,4,5,1,2,0)
# for i in range(len(perm)):
#     j = perm[i]
#     while True:
#         if j == i:
#             break
#         if j < i:
#             print(i, j)
#         j = perm[j]
    

In [4]:
import torchvision
import torch

dataset = torchvision.datasets.FashionMNIST(".", train=True, download=True, transform=torchvision.transforms.ToTensor())
data_loader = torch.utils.data.DataLoader(
    dataset,
    batch_size=64,
    shuffle=True,
    drop_last=True
)
model = torch.nn.Sequential(
    torch.nn.Linear(in_features=784, out_features=256),
    torch.nn.Tanh(),
    torch.nn.Linear(in_features=256, out_features=10),
)
optim = torch.optim.AdamW(model.parameters())
accs = []
for x, y in data_loader:
    x = x.view((-1, 784))
    y_ = model(x)
    loss = torch.nn.functional.cross_entropy(y_, y)
    optim.zero_grad()
    loss.backward()
    optim.step()
    acc = (y_.argmax(dim=-1) == y).float().mean().item()
    accs.append(acc)
accs = torch.tensor(accs)
print((accs[-20:]).mean())

# 3x3
# -> 1x9, 9x1, 3x3
# .view(-1, 3)
# shape 1,9
# .view(-1, 3)
# 3,3

# .shape(3,3)
# .view(-1, 9)
# 1,9

# 5,3,2 - 30
# .shape 1,30 2,15, 3,10, 5,6
# 5,3,2

# .view(-1, 2) -> 15,2

tensor(0.8367)


In [5]:
import numpy as np
# layer1_weights = model[0].weight
# layer2_bias = model[0].bias
models = [
    (model[0].weight.data.T, model[0].bias.data, "layer1"),
    (model[2].weight.data.T, model[2].bias.data, "layer2"),
]
for weight, bias, layer in models:
    xs = weight.numpy()
    ys = bias.numpy()
    
    xs = xs.tobytes()
    ys = ys.tobytes()
    
    with open(layer + "-weight.bin", "wb") as f:
        f.write(xs)
    with open(layer + "-bias.bin", "wb") as f:
        f.write(ys)

In [6]:
model[0].weight.data[0][0]

tensor(-0.0180)

In [7]:
data_loader = torch.utils.data.DataLoader(
    dataset,
    batch_size=100,
    shuffle=False,
)
x, y = next(iter(data_loader))
x = x.view((100, 1, 784))
print(x.shape)
w = model[0].weight.data.T.view(1, 784, 256).repeat((100, 1, 1))
print(w.shape)
# torch.set_printoptions(threshold=2000)
print(torch.bmm(x, w))

torch.Size([100, 1, 784])
torch.Size([100, 784, 256])
tensor([[[ 1.3145, -1.4173, -1.2223,  ...,  4.0972, -3.8360, -1.2674]],

        [[ 4.5715,  5.6116,  2.0371,  ..., -1.1718, -0.1021,  2.5020]],

        [[ 1.0239,  1.1914,  0.5006,  ..., -1.1253,  0.2869,  0.7919]],

        ...,

        [[ 1.4913,  0.3290, -0.8242,  ..., -1.6336,  0.3895, -0.5262]],

        [[ 2.3342,  2.6105, -0.1626,  ..., -1.9459, -0.3953,  0.2675]],

        [[ 0.4969,  1.9527, -0.6844,  ...,  1.5524, -2.1219, -0.3343]]])


In [31]:
print(model[0].weight.data)
print(model[0].bias.data)
print(model[2].weight.data)
print(model[2].bias.data)

tensor([[ 0.0268, -0.0397, -0.0436,  ...,  0.0038, -0.0621,  0.0213],
        [ 0.0267,  0.0572,  0.0585,  ..., -0.0284, -0.0691,  0.0497],
        [ 0.0078,  0.0057, -0.0403,  ..., -0.0126,  0.0398,  0.0244],
        ...,
        [ 0.0255,  0.0196,  0.0090,  ...,  0.0182,  0.0395, -0.0296],
        [-0.0297,  0.0237, -0.0137,  ...,  0.0062, -0.0389, -0.0032],
        [-0.0210, -0.0298, -0.0026,  ..., -0.0068,  0.0032, -0.0044]])
tensor([ 0.0249,  0.0563,  0.0666,  0.0337, -0.0472,  0.1053,  0.0707,  0.0257,
        -0.0253, -0.1374, -0.0259, -0.0356, -0.0486, -0.1249, -0.0231, -0.0416,
        -0.0069, -0.0341, -0.0489, -0.0956, -0.0315,  0.0212, -0.0301,  0.0803,
         0.0449,  0.0979,  0.0976, -0.0876, -0.0083, -0.0189, -0.0297,  0.1159,
         0.0307, -0.0035,  0.0674,  0.0761,  0.0447,  0.0562,  0.1279,  0.1330,
         0.1345,  0.0852,  0.0050, -0.0680, -0.0388,  0.1347, -0.1960, -0.0753,
         0.0778, -0.0996, -0.1284,  0.0190, -0.0054,  0.0499,  0.0453, -0.0011,
      

In [17]:
data_loader = torch.utils.data.DataLoader(
    dataset,
    batch_size=100,
    shuffle=False,
)
x, y = next(iter(data_loader))
x = x.view((100, 1, 784))
w = model[0].weight.data.T.view(1, 784, 256).repeat((100, 1, 1))
# w = torch.nn.Parameter(w)
x = torch.bmm(x, w)
b = model[0].bias.data.view(1, 1, 256)
# b = torch.nn.Parameter(b)
x = x + b

x = torch.tanh(x)
print(model[2].weight.shape, model[2].bias.shape)
w2 = model[2].weight.data.T.reshape(1, 256, 10).repeat((100, 1, 1))
# w2 = torch.nn.Parameter(w2)
b2 = model[2].bias.data.view(1, 1, 10)
# b2 = torch.nn.Parameter(b2)
x = torch.bmm(x, w2)
x = x + b2
print(x.shape)
print(y.shape)
x = torch.nn.Parameter(x)
loss = torch.nn.functional.cross_entropy(x[:,0,:], y)
loss.backward()
x.grad


torch.Size([10, 256]) torch.Size([10])
torch.Size([100, 1, 10])
torch.Size([100])


tensor([[[ 5.6936e-09,  1.9767e-09,  7.3410e-09,  1.7191e-08,  1.8466e-08,
           5.4564e-06,  2.6366e-08,  7.9811e-05,  1.3296e-06, -8.6675e-05]],

        [[-1.5396e-04,  1.9517e-08,  3.0119e-06,  7.5644e-06,  3.4204e-08,
           4.4343e-10,  1.4301e-04,  1.2942e-08,  1.9308e-07,  1.1237e-07]],

        [[-7.0352e-03,  2.6852e-04,  3.4797e-04,  5.4132e-03,  4.5428e-04,
           5.3749e-08,  5.2319e-04,  8.2614e-06,  4.1274e-06,  1.5587e-05]],

        [[ 2.5805e-03,  3.1023e-05,  1.7323e-04, -4.9954e-03,  7.3344e-06,
           3.2709e-09,  2.2018e-03,  4.4232e-07,  6.4173e-07,  4.2010e-07]],

        [[-8.8330e-03,  4.0915e-04,  2.9913e-05,  8.1248e-03,  2.9935e-05,
           3.8101e-09,  2.3472e-04,  8.0341e-07,  3.2236e-06,  5.2016e-07]],

        [[ 1.1421e-05,  2.4739e-07, -4.9433e-05,  3.2922e-06,  1.0483e-05,
           5.2499e-08,  2.3589e-05,  9.2563e-09,  3.2234e-07,  1.6254e-08]],

        [[ 5.2286e-08,  7.5837e-08,  2.0889e-07,  3.4477e-07,  2.9029e-07,
       

In [50]:
x = sp.symbols("x")
y = sp.tanh(x)
y.diff(x)

1 - tanh(x)**2

In [45]:
import sympy as sp
a,b,c = sp.symbols("a,b,c")
denom = sp.exp(a) + sp.exp(b) + sp.exp(c)
a_ = sp.exp(a) / denom
b_ = sp.exp(b) / denom
c_ = sp.exp(c) / denom
# a_.diff(a)
loss = -sp.log(a_)
loss.diff(a).simplify()

(-exp(b) - exp(c))/(exp(a) + exp(b) + exp(c))

In [19]:
import torch
n = torch.arange(3*3*3) + 1
n = n.reshape((3,3,3))
out = 0
ixs = [1,1,1]
for i in range(3):
    out *= n.shape[i]
    out += ixs[i]
    print(out)

n.flatten()[out]

1
4
13


tensor(14)

In [27]:
a =100*1*784
a

78400

In [28]:
b = 1*784*256
b

200704

In [30]:
c = 100*1*256
c

25600

In [12]:
y = ([1, 3, 0, 2, 5, 1,8,4])
y = torch.tensor(y).view(2,4)
print(y)
torch.argmax(y, dim=-1)

tensor([[1, 3, 0, 2],
        [5, 1, 8, 4]])


tensor([1, 2])

In [14]:
np.exp(-0.28814)

np.float64(0.7496566329634485)

In [15]:
-np.log(1/10)

np.float64(2.3025850929940455)