In [1]:
import struct
import numpy as np
import torch
import torchvision

# files = ["fashion-mnist_test.csv", "fashion-mnist_train.csv"]
train_dataset = torchvision.datasets.FashionMNIST(".", train=True, download=True, transform=torchvision.transforms.ToTensor())
test_dataset = torchvision.datasets.FashionMNIST(".", train=False, download=True, transform=torchvision.transforms.ToTensor())

def dump_to_bin(dataset, basename):
    xs, ys = [], []
    data_loader = torch.utils.data.DataLoader(
        dataset,
        batch_size=1,
        shuffle=False,
        drop_last=False
    )
    for x,y in data_loader:
        xs.append(x)
        ys.append(y)

    xs = torch.cat(xs, dim=0)
    ys = torch.cat(ys, dim=0)
    print(xs.shape, xs.dtype, ys.shape, ys.dtype)
    # data = data.split("\n")[1:-1]
    # for line in data:
    #     label, *pixels = line.split(",")
    #     xs.append([float(int(v)) / 255.0 for v in pixels])
    #     ys.append(int(label))
        
    xs = xs.numpy().astype(np.float32) 
    ys = ys.numpy().astype(np.uint8)
    
    xs = xs.tobytes()
    ys = ys.tobytes()
    
    with open(basename + "-data.bin", "wb") as f:
        f.write(xs)
    with open(basename + "-labels.bin", "wb") as f:
        f.write(ys)

dump_to_bin(train_dataset, "train")
dump_to_bin(test_dataset, "test")

torch.Size([60000, 1, 28, 28]) torch.float32 torch.Size([60000]) torch.int64
torch.Size([10000, 1, 28, 28]) torch.float32 torch.Size([10000]) torch.int64


In [2]:
# import torch
# n = torch.arange(30)
# n = n.reshape((5,3,2))
# print(n.shape)
# print(n.flatten())
# n = n.permute((0,1,2))
# print(n[1][1][2])
# print(n.shape)
# n.flatten()

In [3]:
# perm = (3,4,5,1,2,0)
# for i in range(len(perm)):
#     j = perm[i]
#     while True:
#         if j == i:
#             break
#         if j < i:
#             print(i, j)
#         j = perm[j]
    

In [2]:
import torchvision
import torch

dataset = torchvision.datasets.FashionMNIST(".", train=True, download=True, transform=torchvision.transforms.ToTensor())
data_loader = torch.utils.data.DataLoader(
    dataset,
    batch_size=64,
    shuffle=True,
    drop_last=True
)
model = torch.nn.Sequential(
    torch.nn.Linear(in_features=784, out_features=256),
    torch.nn.Tanh(),
    torch.nn.Linear(in_features=256, out_features=10),
)
optim = torch.optim.AdamW(model.parameters())
accs = []
for x, y in data_loader:
    x = x.view((-1, 784))
    y_ = model(x)
    loss = torch.nn.functional.cross_entropy(y_, y)
    optim.zero_grad()
    loss.backward()
    optim.step()
    acc = (y_.argmax(dim=-1) == y).float().mean().item()
    accs.append(acc)
accs = torch.tensor(accs)
print((accs[-20:]).mean())

# 3x3
# -> 1x9, 9x1, 3x3
# .view(-1, 3)
# shape 1,9
# .view(-1, 3)
# 3,3

# .shape(3,3)
# .view(-1, 9)
# 1,9

# 5,3,2 - 30
# .shape 1,30 2,15, 3,10, 5,6
# 5,3,2

# .view(-1, 2) -> 15,2

tensor(0.8484)


In [3]:
import numpy as np
# layer1_weights = model[0].weight
# layer2_bias = model[0].bias
models = [
    (model[0].weight.data.T, model[0].bias.data, "layer1"),
    (model[2].weight.data.T, model[2].bias.data, "layer2"),
]
for weight, bias, layer in models:
    xs = weight.numpy()
    ys = bias.numpy()
    
    xs = xs.tobytes()
    ys = ys.tobytes()
    
    with open(layer + "-weight.bin", "wb") as f:
        f.write(xs)
    with open(layer + "-bias.bin", "wb") as f:
        f.write(ys)

In [4]:
model[0].weight.data[0][0]

tensor(0.0112)

In [5]:
data_loader = torch.utils.data.DataLoader(
    dataset,
    batch_size=100,
    shuffle=False,
)
x, y = next(iter(data_loader))
x = x.view((100, 1, 784))
print(x.shape)
w = model[0].weight.data.T.view(1, 784, 256).repeat((100, 1, 1))
print(w.shape)
# torch.set_printoptions(threshold=2000)
print(torch.bmm(x, w))

torch.Size([100, 1, 784])
torch.Size([100, 784, 256])
tensor([[[-4.5130, -8.6351, -6.3139,  ..., -5.1290,  1.5470,  2.1680]],

        [[ 2.5511,  1.1860, -1.4186,  ...,  0.4405, -4.9776, -0.5403]],

        [[ 0.8648,  0.5664, -0.0372,  ...,  0.3498, -0.9337,  0.1519]],

        ...,

        [[ 1.6060,  2.1047,  1.8908,  ...,  1.4018,  0.5178,  1.0259]],

        [[ 2.4827,  1.2917,  1.5614,  ...,  1.5709, -2.1392,  1.2797]],

        [[-3.6593, -7.9735, -5.8290,  ..., -4.9662, -1.8638,  0.8602]]])


In [6]:
print(model[0].weight.data)
print(model[0].bias.data)
print(model[2].weight.data)
print(model[2].bias.data)

tensor([[ 0.0112, -0.0144,  0.0097,  ...,  0.0105, -0.0067,  0.0403],
        [-0.0126,  0.0487,  0.0258,  ..., -0.0664, -0.0330, -0.0443],
        [ 0.0008, -0.0211, -0.0180,  ...,  0.0066, -0.0244, -0.0109],
        ...,
        [ 0.0020,  0.0268,  0.0257,  ..., -0.1110, -0.0853, -0.0328],
        [-0.0021, -0.0108, -0.0332,  ...,  0.0429,  0.0172,  0.0123],
        [-0.0434, -0.0019, -0.0864,  ..., -0.0261, -0.0310, -0.0540]])
tensor([ 4.2779e-02, -7.1678e-04, -3.5814e-02, -7.7225e-02, -8.9699e-02,
         7.4321e-02,  5.6046e-02,  1.4259e-01, -6.2133e-02, -3.7887e-03,
         7.1710e-02, -1.7525e-01,  7.6363e-03, -5.2154e-02,  5.9575e-02,
        -7.5290e-02,  1.5436e-01, -5.1713e-02, -3.3050e-02, -2.1798e-02,
         1.1739e-01, -1.2614e-02, -1.1925e-01, -9.3000e-02, -1.3659e-01,
        -1.3711e-01, -4.1511e-02, -9.7281e-03,  7.3506e-02, -2.0238e-02,
         1.1280e-01, -6.1096e-02,  1.9372e-02, -2.3311e-02,  5.3811e-02,
         4.3573e-02, -8.7604e-02,  2.7385e-02,  4.4683e

In [21]:
data_loader = torch.utils.data.DataLoader(
    dataset,
    batch_size=100,
    shuffle=False,
)
x, y = next(iter(data_loader))
x = x.view((100, 1, 784))
w = model[0].weight.data.T.view(1, 784, 256).repeat((100, 1, 1))

w = torch.nn.Parameter(w)
w1_ = w
x = torch.bmm(x, w)
b = model[0].bias.data.view(1, 1, 256)
b = torch.nn.Parameter(b)
b1_ = b
x = x + b
x = torch.tanh(x)

w2 = model[2].weight.data.T.reshape(1, 256, 10).repeat((100, 1, 1))
b2 = model[2].bias.data.view(1, 1, 10)
w2 = torch.nn.Parameter(w2)
w2_ = w2
x = torch.bmm(x, w2)
b2 = torch.nn.Parameter(b2)
b2_ = b2
x = x + b2
loss = torch.nn.functional.cross_entropy(x[:,0,:], y)
loss.backward()
print(w1_.grad.flatten()[:10])
print(b1_.grad.flatten()[:10])
print(w2_.grad.flatten()[:10])
print(b2_.grad.flatten()[:10])

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([ 0.0011,  0.0019,  0.0034,  0.0014, -0.0008, -0.0023, -0.0032, -0.0003,
        -0.0015, -0.0031])
tensor([-8.5547e-10, -7.5043e-09, -6.6643e-09, -6.0665e-09, -1.3849e-08,
        -4.6555e-06, -6.7528e-09, -1.6807e-05, -5.8186e-07,  2.2086e-05])
tensor([ 0.0067,  0.0047,  0.0051,  0.0181, -0.0185, -0.0101, -0.0219,  0.0060,
         0.0122, -0.0023])


In [68]:
x_.grad.flatten().argmax(), x_.grad.flatten()[43]

(tensor(43), tensor(0.0081))

In [ ]:
# # c = a + b
# # dl/dc 
# # dl/da
# # dl/db
# dl/da = dl/dc * dc/da 
# dc/da = 1
# dl/db = dl/dc * dc/db
# d(a+b) / da = (da+db) / da  = da/da + db/da => 1 + 0

In [50]:
x = sp.symbols("x")
y = sp.tanh(x)
y.diff(x)

1 - tanh(x)**2

In [45]:
import sympy as sp
a,b,c = sp.symbols("a,b,c")
denom = sp.exp(a) + sp.exp(b) + sp.exp(c)
a_ = sp.exp(a) / denom
b_ = sp.exp(b) / denom
c_ = sp.exp(c) / denom
# a_.diff(a)
loss = -sp.log(a_)
loss.diff(a).simplify()

(-exp(b) - exp(c))/(exp(a) + exp(b) + exp(c))

In [19]:
import torch
n = torch.arange(3*3*3) + 1
n = n.reshape((3,3,3))
out = 0
ixs = [1,1,1]
for i in range(3):
    out *= n.shape[i]
    out += ixs[i]
    print(out)

n.flatten()[out]

1
4
13


tensor(14)

In [27]:
a =100*1*784
a

78400

In [28]:
b = 1*784*256
b

200704

In [30]:
c = 100*1*256
c

25600

In [12]:
y = ([1, 3, 0, 2, 5, 1,8,4])
y = torch.tensor(y).view(2,4)
print(y)
torch.argmax(y, dim=-1)

tensor([[1, 3, 0, 2],
        [5, 1, 8, 4]])


tensor([1, 2])

In [14]:
np.exp(-0.28814)

np.float64(0.7496566329634485)

In [15]:
-np.log(1/10)

np.float64(2.3025850929940455)