In [ ]:
import struct
import numpy as np
import torch
import torchvision

# files = ["fashion-mnist_test.csv", "fashion-mnist_train.csv"]
train_dataset = torchvision.datasets.FashionMNIST(".", train=True, download=True, transform=torchvision.transforms.ToTensor())
test_dataset = torchvision.datasets.FashionMNIST(".", train=False, download=True, transform=torchvision.transforms.ToTensor())

def dump_to_bin(dataset, basename):
    xs, ys = [], []
    data_loader = torch.utils.data.DataLoader(
        dataset,
        batch_size=1,
        shuffle=False,
        drop_last=False
    )
    for x,y in data_loader:
        xs.append(x)
        ys.append(y)

    xs = torch.cat(xs, dim=0)
    ys = torch.cat(ys, dim=0)
    print(xs.shape, xs.dtype, ys.shape, ys.dtype)
    # data = data.split("\n")[1:-1]
    # for line in data:
    #     label, *pixels = line.split(",")
    #     xs.append([float(int(v)) / 255.0 for v in pixels])
    #     ys.append(int(label))
        
    xs = xs.numpy().astype(np.float32) 
    ys = ys.numpy().astype(np.uint8)
    
    xs = xs.tobytes()
    ys = ys.tobytes()
    
    with open(basename + "-data.bin", "wb") as f:
        f.write(xs)
    with open(basename + "-labels.bin", "wb") as f:
        f.write(ys)

dump_to_bin(train_dataset, "train")
dump_to_bin(test_dataset, "test")

torch.Size([60000, 1, 28, 28]) torch.float32 torch.Size([60000]) torch.int64
torch.Size([10000, 1, 28, 28]) torch.float32 torch.Size([10000]) torch.int64


In [2]:
# import torch
# n = torch.arange(30)
# n = n.reshape((5,3,2))
# print(n.shape)
# print(n.flatten())
# n = n.permute((0,1,2))
# print(n[1][1][2])
# print(n.shape)
# n.flatten()

In [3]:
# perm = (3,4,5,1,2,0)
# for i in range(len(perm)):
#     j = perm[i]
#     while True:
#         if j == i:
#             break
#         if j < i:
#             print(i, j)
#         j = perm[j]
    

In [3]:
import torchvision
import torch

dataset = torchvision.datasets.FashionMNIST(".", train=True, download=True, transform=torchvision.transforms.ToTensor())
data_loader = torch.utils.data.DataLoader(
    dataset,
    batch_size=64,
    shuffle=True,
    drop_last=True
)
model = torch.nn.Sequential(
    torch.nn.Linear(in_features=784, out_features=256),
    torch.nn.Tanh(),
    torch.nn.Linear(in_features=256, out_features=10),
)
optim = torch.optim.Adam(model.parameters())
accs = []
for x, y in data_loader:
    x = x.view((-1, 784))
    y_ = model(x)
    loss = torch.nn.functional.cross_entropy(y_, y)
    optim.zero_grad()
    loss.backward()
    optim.step()
    acc = (y_.argmax(dim=-1) == y).float().mean().item()
    accs.append(acc)
accs = torch.tensor(accs)
print((accs[-20:]).mean())

# 3x3
# -> 1x9, 9x1, 3x3
# .view(-1, 3)
# shape 1,9
# .view(-1, 3)
# 3,3

# .shape(3,3)
# .view(-1, 9)
# 1,9

# 5,3,2 - 30
# .shape 1,30 2,15, 3,10, 5,6
# 5,3,2

# .view(-1, 2) -> 15,2

tensor(0.8508)


In [4]:
import numpy as np
# layer1_weights = model[0].weight
# layer2_bias = model[0].bias
models = [
    (model[0].weight.data.T, model[0].bias.data, "layer1"),
    (model[2].weight.data.T, model[2].bias.data, "layer2"),
]
for weight, bias, layer in models:
    xs = weight.numpy()
    ys = bias.numpy()
    
    xs = xs.tobytes()
    ys = ys.tobytes()
    
    with open(layer + "-weight.bin", "wb") as f:
        f.write(xs)
    with open(layer + "-bias.bin", "wb") as f:
        f.write(ys)

In [5]:
model[0].weight.data[0][0]

tensor(-0.0512)

In [5]:
data_loader = torch.utils.data.DataLoader(
    dataset,
    batch_size=100,
    shuffle=False,
)
x, y = next(iter(data_loader))
x = x.view((100, 1, 784))
print(x.shape)
w = model[0].weight.data.T.view(1, 784, 256).repeat((100, 1, 1))
print(w.shape)
# torch.set_printoptions(threshold=2000)
print(torch.bmm(x, w))

torch.Size([100, 1, 784])
torch.Size([100, 784, 256])
tensor([[[-4.5130, -8.6351, -6.3139,  ..., -5.1290,  1.5470,  2.1680]],

        [[ 2.5511,  1.1860, -1.4186,  ...,  0.4405, -4.9776, -0.5403]],

        [[ 0.8648,  0.5664, -0.0372,  ...,  0.3498, -0.9337,  0.1519]],

        ...,

        [[ 1.6060,  2.1047,  1.8908,  ...,  1.4018,  0.5178,  1.0259]],

        [[ 2.4827,  1.2917,  1.5614,  ...,  1.5709, -2.1392,  1.2797]],

        [[-3.6593, -7.9735, -5.8290,  ..., -4.9662, -1.8638,  0.8602]]])


In [5]:
print(model[0].weight.data)
print(model[0].bias.data)
print(model[2].weight.data)
print(model[2].bias.data)

tensor([[-0.0071,  0.0322,  0.0114,  ..., -0.0219,  0.0032,  0.0240],
        [-0.0124, -0.0690, -0.0581,  ..., -0.0401, -0.0433,  0.0324],
        [-0.0239, -0.0525,  0.0061,  ..., -0.0268,  0.0215, -0.0345],
        ...,
        [-0.0262,  0.0220,  0.0135,  ..., -0.0359, -0.0317,  0.0137],
        [-0.0293, -0.0524, -0.0122,  ...,  0.0427,  0.0129,  0.0176],
        [ 0.0421,  0.0330,  0.0310,  ...,  0.0866,  0.0976,  0.0679]])
tensor([-0.0712, -0.1544,  0.1700, -0.0963,  0.0006,  0.1068,  0.0833, -0.0643,
        -0.1234,  0.0347,  0.0217,  0.0646, -0.0655,  0.0834, -0.0750, -0.0445,
        -0.1560,  0.0920, -0.1393,  0.0254,  0.1337, -0.1705, -0.0983, -0.1095,
        -0.0038, -0.0795,  0.0524, -0.1304, -0.1692,  0.0336, -0.0607, -0.0774,
        -0.0668,  0.1359,  0.1508, -0.0710, -0.1867,  0.1066, -0.0074, -0.0478,
        -0.0393,  0.0197, -0.0800, -0.0022, -0.0298,  0.1663,  0.1086,  0.0705,
        -0.0864, -0.0350, -0.0372,  0.0669,  0.0411,  0.1623, -0.0981, -0.1700,
      

In [12]:
data_loader = torch.utils.data.DataLoader(
    dataset,
    batch_size=100,
    shuffle=False,
)
x, y = next(iter(data_loader))
x = x.view((100, 1, 784))
w = model[0].weight.data.T.view(1, 784, 256).repeat((100, 1, 1))
b = model[0].bias.data.view(1, 1, 256)
w2 = model[2].weight.data.T.reshape(1, 256, 10).repeat((100, 1, 1))
b2 = model[2].bias.data.view(1, 1, 10)

w = torch.nn.Parameter(w)
b = torch.nn.Parameter(b)
w2 = torch.nn.Parameter(w2)
b2 = torch.nn.Parameter(b2)



optim = torch.optim.Adam([w,b,w2,b2], lr=0.1)

for _ in range(10):

    w1_ = w
    h1 = torch.bmm(x, w)
    b1_ = b
    h1 = h1 + b
    h1 = torch.tanh(h1)
    
    w2_ = w2
    h2 = torch.bmm(h1, w2)
    b2_ = b2
    h2 = h2 + b2
    loss = torch.nn.functional.cross_entropy(h2[:,0,:], y)
    loss.backward()
    optim.zero_grad()
    optim.step()

    
    print(w.flatten()[:10])
    print(b.flatten()[:10])
    print(w2.flatten()[:10])
    print(b2.flatten()[:10])
    print("=============")
# print(w1_.grad.flatten()[:10])
# print(b1_.grad.flatten()[:10])
# print(w2_.grad.flatten()[:10])
# print(b2_.grad.flatten()[:10])

tensor([-0.0005, -0.0093,  0.0190, -0.0047,  0.0021, -0.0214, -0.0318, -0.0229,
         0.0221, -0.0552], grad_fn=<SliceBackward0>)
tensor([ 0.1743, -0.0227,  0.1201,  0.0301,  0.0318, -0.0502,  0.0169, -0.0781,
         0.0410, -0.0166], grad_fn=<SliceBackward0>)
tensor([ 0.0599,  0.0341,  0.0735,  0.0949, -0.0968,  0.0286,  0.0776,  0.0350,
        -0.0829, -0.1178], grad_fn=<SliceBackward0>)
tensor([ 0.0697, -0.0256, -0.0219,  0.0468, -0.0505,  0.0493, -0.0332,  0.0200,
        -0.0800, -0.0540], grad_fn=<SliceBackward0>)
tensor([-0.0005, -0.0093,  0.0190, -0.0047,  0.0021, -0.0214, -0.0318, -0.0229,
         0.0221, -0.0552], grad_fn=<SliceBackward0>)
tensor([ 0.1743, -0.0227,  0.1201,  0.0301,  0.0318, -0.0502,  0.0169, -0.0781,
         0.0410, -0.0166], grad_fn=<SliceBackward0>)
tensor([ 0.0599,  0.0341,  0.0735,  0.0949, -0.0968,  0.0286,  0.0776,  0.0350,
        -0.0829, -0.1178], grad_fn=<SliceBackward0>)
tensor([ 0.0697, -0.0256, -0.0219,  0.0468, -0.0505,  0.0493, -0.0332

In [68]:
x_.grad.flatten().argmax(), x_.grad.flatten()[43]

(tensor(43), tensor(0.0081))

In [ ]:
# # c = a + b
# # dl/dc 
# # dl/da
# # dl/db
# dl/da = dl/dc * dc/da 
# dc/da = 1
# dl/db = dl/dc * dc/db
# d(a+b) / da = (da+db) / da  = da/da + db/da => 1 + 0

In [50]:
x = sp.symbols("x")
y = sp.tanh(x)
y.diff(x)

1 - tanh(x)**2

In [45]:
import sympy as sp
a,b,c = sp.symbols("a,b,c")
denom = sp.exp(a) + sp.exp(b) + sp.exp(c)
a_ = sp.exp(a) / denom
b_ = sp.exp(b) / denom
c_ = sp.exp(c) / denom
# a_.diff(a)
loss = -sp.log(a_)
loss.diff(a).simplify()

(-exp(b) - exp(c))/(exp(a) + exp(b) + exp(c))

In [19]:
import torch
n = torch.arange(3*3*3) + 1
n = n.reshape((3,3,3))
out = 0
ixs = [1,1,1]
for i in range(3):
    out *= n.shape[i]
    out += ixs[i]
    print(out)

n.flatten()[out]

1
4
13


tensor(14)

In [27]:
a =100*1*784
a

78400

In [28]:
b = 1*784*256
b

200704

In [30]:
c = 100*1*256
c

25600

In [12]:
y = ([1, 3, 0, 2, 5, 1,8,4])
y = torch.tensor(y).view(2,4)
print(y)
torch.argmax(y, dim=-1)

tensor([[1, 3, 0, 2],
        [5, 1, 8, 4]])


tensor([1, 2])

In [14]:
np.exp(-0.28814)

np.float64(0.7496566329634485)

In [15]:
-np.log(1/10)

np.float64(2.3025850929940455)